# TODO: change site_name and repo_url to match your repo
site_name: "Dynatrace Enablement Lab: Business Observability"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/enablement-browser-dem-biz-observability"
nav:
  - '1. About': index.md
  - '2. Getting started': 2-getting-started.md
  - '3. Customer Journey vs Business Journey': 3-customer-business-journey.md
  - '4. Real User Monitoring': 4-real-user-monitoring.md
  - '5. Business Observability with RUM': 5-business-observability-rum.md
  - '6. Business Observability Automation': 6-business-observability-automation.md
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.copy
    
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: '#'
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["docs"]
  - attr_list
plugins:
    - search
